# Generated by Django 4.0.4 on 2022-05-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.CharField(max_length=300)),
                ('cuerpo', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
