# Generated by Django 4.0.4 on 2022-05-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posteos', '0002_alter_post_cuerpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
