# Generated by Django 4.0.4 on 2022-06-01 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Posteos', '0004_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
