# Generated by Django 4.0.4 on 2022-06-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posteos', '0006_alter_avatar_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Profesor',
        ),
    ]
