# Generated by Django 4.0.4 on 2022-06-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posteos', '0008_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media'),
        ),
    ]
